### ISSUE TITLE
Why are directories _config, controller, model, in the repository?

### ISSUE THREAD

**Issue by ashleysommer** [CSIRO-enviro-informatics/pyldapi#6]
There are empty directories `_config`, `controller`, `model`, in the repository.
They only contain old cache files, and none of these directories seem to be used in the project.

**Comment by nicholascar** [comment]
fixed by https://github.com/CSIRO-enviro-informatics/pyldapi/commit/60c29e3cbe4c734806a765c39c8f4cad1469cb72
